bai tap lon mon t5/Controllers/LamDeThiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bai_tap_lon_mon_t5.Models;

namespace bai_tap_lon_mon_t5.Controllers
{
    public class LamDeThiController : Controller
    {
        List<CAUHOI> lstCH = new List<CAUHOI>();
        // GET: LamDeThi
        public ActionResult Index(int id)
        {
            id = 1;
            
            DETHI dt = new DETHI();
            dt = dt.ChiTietDeThi(id);
            ViewData["DSCHDT"] =dt.ListCauHoi;
            
            ViewBag.id = id;
            
            return View();
        }
        [HttpPost]
        public ActionResult KetQua()
        {
            List<string> lstdapan = new List<string>();

            string id = Request.Form["id"];


            string a;
            for (int i = 1; i <= 10; i++)
            {
                a = string.Concat("CauHoi", i.ToString());
                if (Request.Form[a] == null)
                {
                    lstdapan.Add("Sai");
                }
                if (Request.Form[a] != null)
                {
                    lstdapan.Add(Request.Form[a]);
                }
            }
            DETHI dt = new DETHI();
            dt = dt.ChiTietDeThi(int.Parse(id));
            lstCH = dt.ListCauHoi;
            int count = 0;
            for (int i = 0; i <= 9; i++)
            {
                if (lstCH[i].DapAnDung.ToString().Trim().ToLower().Equals(lstdapan[i].ToString().Trim().ToLower()))
                {
                    count++;
                }
            }
            ViewBag.made = id;
            ViewBag.a = count;
            ViewBag.diem = count * 0.25;
            return View();
        }
    }
}

bai tap lon mon t5/Views/LamDeThi/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutLamDE.cshtml";
}
@using bai_tap_lon_mon_t5.Models;


@{


    List<CAUHOI> lst = (List<CAUHOI>)ViewData["DSCHDT"];

}

@using (Html.BeginForm("KetQua", "LamDeThi", FormMethod.Post, new { name = "frmDeThi" }))
{
    <br />
    <br />
    <h1 style="color:red;text-align:center;">MÃ ĐỀ THI:<span><input type="text" name="id" value=@ViewBag.id readonly="true" style="color: red;border: none;width: 122px;padding-left: 12px;"></span></h1>
    <br />
    int i = 1;

    foreach (CAUHOI sp in lst)
    {
        string str = string.Concat("CauHoi", i.ToString());
        <div class="form-group" style="border-bottom: 1px solid black; ">
            <h4> Câu @i . @sp.NoiDung </h4>
            <p style="display: inline-block;width: 100%;border: 1px solid #80808087;border-radius: 5px;border-radius: 1px solid gray;">
                <input type="radio" name="@str" style="margin: 16px 25px;" value="A" />
                <span>A. @sp.DapAnA</span>
            </p>
            <p style="display: inline-block;width: 100%;border: 1px solid #80808087;border-radius: 5px;border-radius: 1px solid gray;">
                <input type="radio" name="@str" style="margin: 16px 25px;" value="B" />
                <span>B. @sp.DapAnB</span>
            </p>  <p style="display: inline-block;width: 100%;border: 1px solid #80808087;border-radius: 5px;border-radius: 1px solid gray;">
                <input type="radio" name="@str" style="margin: 16px 25px;" value="C" />
                <span>C. @sp.DapAnC</span>
            </p>
            <p style="display: inline-block;width: 100%;border: 1px solid #80808087;border-radius: 5px;border-radius: 1px solid gray;">
                <input type="radio" name="@str" style="margin: 16px 25px;" value="D" />
                <span>D. @sp.DapAnD</span>
            </p>
        </div>

        i++;
    }
    <div style="text-align:left">
        <h1 style="border: 1px solid black;width: 150px;display: block;position: fixed;top: 100px;right: 10px;font-size: 1.5rem;padding-left: 12px;">
            <input type="text" readonly="true" id="h" value="01" style="width: 30px;border: 0;font-size: 25px;">
            <span style="font-size: 25px;">:</span>
            <input type="text" readonly="true" id="m" value="00" style="width: 30px; border: 0; font-size: 25px;">
            <span style="font-size: 25px;">:</span>
            <input type="text" readonly="true" id="s" value="30" style="width: 30px;border: 0;font-size: 25px;">
        </h1>

        <script type="text/javascript">

                var h = window.document.getElementById('h').value;
                var m = window.document.getElementById('m').value;
                var s = window.document.getElementById('s').value;
                function demnguoc() {
                    s = s - 1;

                    if (s === -1) {
                        m -= 1;
                        s = 59;
                    }

                    if (m === -1) {
                        h -= 1;
                        m = 59;
                    }
                    if (h != -1) {
                        window.document.getElementById('h').value = h;
                        window.document.getElementById('m').value = m;
                        window.document.getElementById('s').value = s;
                        setTimeout("demnguoc()", 1000);
                    }
                    else
                        window.document.frmDeThi.submit();
                }
                demnguoc();
        </script>
    </div>
    <div class="container">

        <input type="submit" value="Kết Thúc" name="SmKetThuc" style="margin-left: 360px; background: red;outline: none; border-radius: 20px;padding: 1px 60px;">

    </div>
}