bai tap lon mon t5/Models/CAUHOI.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace bai_tap_lon_mon_t5.Models
{
    public class CAUHOI
    {

        private int maCauHoi;
        private string noiDung;
        private string loiGiai;
        private string dapAnA;
        private string dapAnB;
        private string dapAnC;
        private string dapAnD;
        private string dapAnDung;
        private string IMG;
        private string doKho;
        private int vungKienThuc;
        private int loaiCauHoi;
        private int maDeThi;
        private int maGiaoVien;
    
        public int MaCauHoi { get => maCauHoi; set => maCauHoi = value; }
        public string NoiDung { get => noiDung; set => noiDung = value; }
        public string LoiGiai { get => loiGiai; set => loiGiai = value; }
        public string DapAnA { get => dapAnA; set => dapAnA = value; }
        public string DapAnB { get => dapAnB; set => dapAnB = value; }
        public string DapAnC { get => dapAnC; set => dapAnC = value; }
        public string DapAnD { get => dapAnD; set => dapAnD = value; }
        public string DapAnDung { get => dapAnDung; set => dapAnDung = value; }
        public string IMG1 { get => IMG; set => IMG = value; }
        public string DoKho { get => doKho; set => doKho = value; }
        public int VungKienThuc { get => vungKienThuc; set => vungKienThuc = value; }
        public int LoaiCauHoi { get => loaiCauHoi; set => loaiCauHoi = value; }
        public int MaDeThi { get => maDeThi; set => maDeThi = value; }
        public int MaGiaoVien { get => maGiaoVien; set => maGiaoVien = value; }
    
        public CAUHOI TimCauHoi(CAUHOI a)
        {
            return null;
        }
        public CAUHOI ThemCauHoi(CAUHOI a)
        {
            SqlConnection con = new SqlConnection();
            ConnectSQL c = new ConnectSQL();
            con = c.Connect();
            con.Open();
            SqlCommand sc = new SqlCommand("pc_ThemCauHoi", con);
            //sc.Parameters.Add("@MaCauHoi", a.MaCauHoi);
            sc.Parameters.Add(new SqlParameter("@noiDung"        , a.NoiDung.ToString()));
            sc.Parameters.Add(new SqlParameter("@loiGiai"        , a.LoiGiai.ToString()));
            sc.Parameters.Add(new SqlParameter("@dapAnA"     , a.DapAnA.ToString()));
            sc.Parameters.Add(new SqlParameter("@dapAnB"      , a.DapAnB.ToString()));
            sc.Parameters.Add(new SqlParameter("@dapAnC"    , a.DapAnC.ToString()));
            sc.Parameters.Add(new SqlParameter("@dapAnD"   , a.DapAnD.ToString()));
            sc.Parameters.Add(new SqlParameter("@dapAnDung"      ,a.DapAnDung.ToString()));
            sc.Parameters.Add(new SqlParameter("@IMG"        ,      a.IMG1.ToString()));
            sc.Parameters.Add(new SqlParameter("@doKho"          , a.DoKho.ToString()));
            sc.Parameters.Add(new SqlParameter("@vungKienThuc"       , a.VungKienThuc.ToString()));
            sc.Parameters.Add(new SqlParameter("@loaiCauHoi"     , a.LoaiCauHoi.ToString()));
            sc.CommandType = CommandType.StoredProcedure;
            sc.ExecuteNonQuery();
            con.Close();
            return a;
            
        }
        public CAUHOI SuaCauHoi(CAUHOI a)
        {
            return null;
        }
        public CAUHOI XoaCauHoi(CAUHOI a)
        {

            return null;
        }
       
        public void SetData(FormCollection fc )
        {
            //maCauHoi = int.Parse(dr["maCauHoi"].ToString());//mã tự tăng nên không cần
            NoiDung = fc["noiDung"].ToString();
            LoiGiai     = fc["loiGiai"].ToString();
            DapAnA      = fc["dapAnA"].ToString();
            DapAnB      = fc["dapAnB"].ToString();
            DapAnC      = fc["dapAnC"].ToString();
            DapAnD      = fc["dapAnD"].ToString();
            DapAnDung   = fc["dapAnDung"].ToString();
            IMG1         = fc["IMG"].ToString();
            DoKho       = fc["doKho"].ToString();
            VungKienThuc = int.Parse(fc["vungKienThuc"].ToString());
            LoaiCauHoi   = int.Parse(fc["loaiCauHoi"].ToString());
        }
        public void SetData(DataRow dr)
        {
            MaCauHoi = int.Parse(dr["maCauHoi"].ToString());//mã tự tăng nên không cần
            NoiDung =   dr["noiDung"].ToString();
            LoiGiai =   dr["loiGiai"].ToString();
            DapAnA =    dr["dapAnA"].ToString();
            DapAnB =    dr["dapAnB"].ToString();
            DapAnC =    dr["dapAnC"].ToString();
            DapAnD =    dr["dapAnD"].ToString();
            DapAnDung = dr["dapAnDung"].ToString();
            IMG1 =      dr["IMG"].ToString();
            DoKho =     dr["doKho"].ToString();
            //VungKienThuc = int.Parse(dr["vungKienThuc"].ToString());
            //LoaiCauHoi = int.Parse(dr["loaiCauHoi"].ToString());
        }       
        public List<CAUHOI> GetAll()
        {
            List<CAUHOI> lst = new List<CAUHOI>();
            SqlConnection con = new SqlConnection();
            ConnectSQL c = new ConnectSQL();
            con = c.Connect();
            con.Open();
            SqlDataAdapter da = new SqlDataAdapter("select *from CAUHOI", con);
            DataTable dt = new DataTable();
            da.Fill(dt);
            con.Close();
            lst = new List<CAUHOI>();
            foreach (DataRow dr in dt.Rows)
            {
                CAUHOI sp = new CAUHOI();
                sp.SetData(dr);
                lst.Add(sp);
            }
            return lst;
        }
        public CAUHOI GetSingle(int id)
        {
            SqlConnection con = new SqlConnection();
            ConnectSQL c = new ConnectSQL();
            con = c.Connect();
            con.Open();
            SqlDataAdapter da = new SqlDataAdapter("select *from CAUHOI where maCauHoi=" + id.ToString(), con);
            DataTable dt = new DataTable();
            da.Fill(dt);
            con.Close();
            if (dt.Rows.Count == 1)
            {
                CAUHOI sp = new CAUHOI();
                sp.SetData(dt.Rows[0]);
                return sp;
            }
            else return null;
        }
    }
   
}

bai tap lon mon t5/Controllers/CauHoiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bai_tap_lon_mon_t5.Models;
namespace bai_tap_lon_mon_t5.Controllers
{
    public class CauHoiController : Controller
    {
        // GET: CauHoi

       
        public ActionResult ThemTC()
        {
            return View();
        }
        public ActionResult ThemCauHoiUI()
        {
            return View();
        }
        public ActionResult ThemCauHoi(FormCollection fc)
        {
            var m = new CAUHOI();
            m.SetData(fc);
            m.ThemCauHoi(m);
            return RedirectToAction("ThemTC");
        }
        public ActionResult GoiDeUI()
        {
            return View();
        }


    }
}

bai tap lon mon t5/Views/CauHoi/GoiDeUI.cshtml
@{
    ViewBag.Title = "GoiDeUI";
    Layout = "~/Views/Shared/_LayoutLamDE.cshtml";
}

<h2>GoiDeUI</h2>
<div>
    <h1>Giáo Viên: Hoàng Minh Đại</h1>
    <h1>Mã GV:1</h1>
    <h1><a style="color:red;" href="@Url.Action("ThemCauHoiUI","CauHoi",new { id=1})"> Thêm Câu Hỏi</a></h1>
</div>

bai tap lon mon t5/Views/CauHoi/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutLamDE.cshtml";
}

<style>
    .headList {
        float: left;
        width: 150px;
        font-size: 25px;
    }

    .headRow {
        float: left;
        width: 250px;
    }
</style>
<div style="text-align:center">


    @using (Html.BeginForm("ThemCauHoi", "CauHoi", FormMethod.Post))
    {
        <div class="headList"> Noi dung</div>
        <div class="headRow"><input type="text" name="noiDung" /></div>
        <div style="clear:both"></div>
        <div class="headList"> loiGiai</div>
        <div class="headRow"><input type="text" name="loiGiai" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnA</div>
        <div class="headRow"><input type="text" name="dapAnA" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnB</div>
        <div class="headRow"><input type="text" name="dapAnB" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnC</div>
        <div class="headRow"><input type="text" name="dapAnC" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnD</div>
        <div class="headRow"><input type="text" name="dapAnD" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnDung</div>
        <div class="headRow"><input type="text" name="dapAnDung" /></div>
        <div style="clear:both"></div>
        <div class="headList"> IMG</div>
        <div class="headRow"><input type="text" name="IMG" /></div>
        <div style="clear:both"></div>
        <div class="headList"> doKho </div>
        <div class="headRow"><input type="text" name="doKho" /></div>
        <div style="clear:both"></div>
        <div class="headList"> vungKienThuc</div>
        <div class="headRow"><input type="text" name="vungKienThuc" /></div>
        <div style="clear:both"></div>
        <div class="headList"> loaiCauHoi</div>
        <div class="headRow"><input type="text" name="loaiCauHoi" /></div>
        <div style="clear:both"></div>
        <input class="headRow" type="submit" value="Them" />
    }
</div>

bai tap lon mon t5/Views/CauHoi/ThemCauHoiUI.cshtml
@{
    ViewBag.Title = "ThemCauHoiUI";
    Layout = "~/Views/Shared/_LayoutLamDE.cshtml";
}

<style>
    .headList {
        float: left;
        width: 150px;
        font-size: 25px;
    }

    .headRow {
        float: left;
        width: 250px;
    }
</style>
<div style="text-align:center">

    <h2>Thêm Thông Tin Câu Hỏi</h2>
    <br />

    @using (Html.BeginForm("ThemCauHoi", "CauHoi", FormMethod.Post))
    {
        <div class="headList"> Noi dung</div>
        <div class="headRow"><input type="text" name="noiDung" /></div>
        <div style="clear:both"></div>
        <div class="headList"> loiGiai</div>
        <div class="headRow"><input type="text" name="loiGiai" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnA</div>
        <div class="headRow"><input type="text" name="dapAnA" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnB</div>
        <div class="headRow"><input type="text" name="dapAnB" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnC</div>
        <div class="headRow"><input type="text" name="dapAnC" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnD</div>
        <div class="headRow"><input type="text" name="dapAnD" /></div>
        <div style="clear:both"></div>
        <div class="headList"> dapAnDung</div>
        <div class="headRow"><input type="text" name="dapAnDung" /></div>
        <div style="clear:both"></div>
        <div class="headList"> IMG</div>
        <div class="headRow"><input type="text" name="IMG" /></div>
        <div style="clear:both"></div>
        <div class="headList"> doKho </div>
        <div class="headRow"><input type="text" name="doKho" /></div>
        <div style="clear:both"></div>
        <div class="headList"> vungKienThuc</div>
        <div class="headRow"><input type="text" name="vungKienThuc" /></div>
        <div style="clear:both"></div>
        <div class="headList"> loaiCauHoi</div>
        <div class="headRow"><input type="text" name="loaiCauHoi" /></div>
        <div style="clear:both"></div>
        <input class="headRow" type="submit" value="Them" />
    }
</div>

bai tap lon mon t5/Views/CauHoi/ThemTC.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutLamDE.cshtml";
}

<h1 style="color:red">Ban da them thanh cong</h1>